### ISSUE TITLE
When will the code and data be released

### ISSUE THREAD

**Issue by renmada** [TIBHannover/formula_gan#1]

**Comment by SpringsteinM** [comment]
Sorry for the delay due to some other deadlines the upload of the code has been delayed a bit. We will try to upload the source here in the next two weeks and provide a docker image for it.

**Comment by ZK-Zhou** [comment]
now after two weeks

**Comment by SpringsteinM** [comment]
Sorry for the delay again. I added the code for the generator to synthesize the data and a short description of the project. I will now upload the datasets and the code for the recognition model in the next few days.

**Comment by lawsonxwl** [comment]
> 
Thanks for the good work, if I want to train the GAN model on my own dataset, what should I do?

**Comment by lawsonxwl** [comment]
> Sorry for the delay again. I added the code for the generator to synthesize the data and a short description of the project. I will now upload the datasets and the code for the recognition model in the next few days.

Thanks for the good work, if I want to train the GAN model on my own dataset, what should I do?

**Comment by SpringsteinM** [comment]
Sorry, I've been on the road for some conferences the last few weeks. In general, I would advise against relying on this code, as it is now significantly outdated. We had experimented internally with some stroke diffusion models that at least with shorter formulas could achieve much more realistic results with less artifacts. (Troy Luhman and Eric Luhman. Diffusion models for handwriting generation.)
