### ISSUE TITLE
All test results are blank images.

### ISSUE THREAD

**Issue by fantuanliu** [TIBHannover/formula_gan#4]
I used the testing method provided in the readme, but all the generated images have only a blank background. Can you please let me know the reason for this?

**Comment by SpringsteinM** [comment]
I have downloaded the script again and repeated all the steps. All images are generated in the folder /data/output/ without error message. The original script also only has the following outputs for me:

```
Param count for Gs initialized parameters: 13134529
Param count for Ds initialized parameters: 4879297
/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0

```
